name: e_commerce
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  dio: ^4.0.6
  flutter_riverpod: ^1.0.4
  flutter_localizations:
    sdk: flutter
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.5

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/

  
  
  
  
  
  
  
  
  
  
